# using git as backend store
backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
site_url: https://loquacious-cuchufli-e77e18.netlify.app
editor:
  preview: true
locale: 'fr'

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ en, fr ]
  default_locale: en

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}--{{year}}{{slug}}" # Filename template, e.g., DD-MM-YYYY-title.md
    nested:
      depth: 100 
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "content/page" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
